export const data = [
    {
        id:1,
        imgg:"./images/Alex Kipkorir.jpg",
        name: "Alex Kipkorir",
        proff: "Photographer",
        isActive: true,
    },
    {
        id:2,
        imgg: "./images/Difina.jpg",
        name: "Difina Wamboi",
        proff: "Doctor",
        isActive: true,
    },
    {
        id:3,
        imgg: "./images/Elvis.jpg",
        name: "Elvis Muiruri",
        proff: "Programmer",
        isActive: true,
    },
    {
        id:4,
        imgg: "./images/shikole.jpg",
        name: "Shikole Wanjogi",
        proff: "Engineer",
        isActive: false,
    },
    {
        id:5,
        imgg: "./images/burna.jpg",
        name: "Burna Boy",
        proff: "Artist",
        isActive: false,
    },
    {
        id:6,
        imgg:"./images/Alex Kipkorir.jpg",
        name: "Alex Kipkorir",
        proff: "Photographer",
        isActive: true,
    },
    {
        id:7,
        imgg: "./images/Difina.jpg",
        name: "Difina Wamboi",
        proff: "Doctor",
        isActive: true,
    },
    {
        id:8,
        imgg: "./images/Elvis.jpg",
        name: "Elvis Muiruri",
        proff: "Programmer",
        isActive: true,
    },
    {
        id:9,
        imgg: "./images/shikole.jpg",
        name: "Shikole Wanjogi",
        proff: "Engineer",
        isActive: false,
    },
    {
        id:10,
        imgg: "./images/burna.jpg",
        name: "Burna Boy",
        proff: "Artist",
        isActive: false,
    },
];